# Generated by Django 3.1.7 on 2021-06-12 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Parroquias',
            },
        ),
        migrations.CreateModel(
            name='BarrioCiudadela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero_viviendas', models.IntegerField(verbose_name='Cantidad de viviendas')),
                ('numero_parques', models.IntegerField(verbose_name='Cantidad de parques')),
                ('numero_edificios', models.IntegerField(verbose_name='Cantidad de edificios')),
                ('id_parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrios', to='ordenamiento.parroquia')),
            ],
            options={
                'verbose_name_plural': 'Barrios o ciudadelas',
            },
        ),
    ]
