# Generated by Django 3.1.7 on 2021-06-19 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0002_auto_20210611_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barriociudadela',
            name='id_parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parroquias', to='ordenamiento.parroquia'),
        ),
        migrations.AlterField(
            model_name='barriociudadela',
            name='numero_parques',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], verbose_name='Cantidad de parques'),
        ),
    ]
